### ISSUE TITLE
Why is my name in some source code

### ISSUE THREAD

**Issue by markknol** [hypersurge/awe6#31]
Hi,

This is just random question. I saw my name/blog is included in [some files](https://github.com/hypersurge/awe6/search?q=mark+knol&unscoped_q=mark+knol) 😃  I was wondering why. I never contributed, and wonder where the code is coming from or why you choose to add my name. I don't mind being mentioned, I'm just curious why.

Btw this looks like a great library.

**Comment by hypersurge** [comment]
Thank you Mark for your (indirect) contribution here:
https://blog.stroep.nl/2014/01/haxe-macros/

It was appropriate to credit "Mark Knol" as an author on these specific files because the bulk of the awe6 autoBuild macro implementation followed Mark's approach.  The macros' purpose is to provide autoCompletion for static Asset filenames and Config XML nodes (reducing development time and increasing accuracy of dependencies).  Such macros provide a clear example of how Haxe adds value to the game development process.

**Comment by markknol** [comment]
Ahh oh thats it. Makes sense.
Thanks for letting know. Cool to see you are using this! 

Indeed, Haxe is great for such stuff.
